baseURL = "https://mkeutgen.github.io/"
languageCode = "en-us"
title = "Maxime Keutgen"
theme = "archie"
copyright = "Maxime Keutgen"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
mode = "auto" # light, dark, or auto
useCDN = false
subtitle = "Studying carbon and oxygen in the ocean, using novel statistical tools."
customcss = ["css/custom.css"]
customCSS = ["css/custom.css"]

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/maxime-keutgen-de-greef/"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/mkeutgen"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:maximek@princeton.edu"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "CV"
url = "/cv"
weight = 4

[[menu.main]]
name = "Publications"
url = "/publications"
weight = 5

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 6
